use ethtool to check network status

diff --git a/pipework b/pipework
--- a/pipework
+++ b/pipework
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
 case "$1" in
@@ -8,7 +8,7 @@ case "$1" in
 esac
 
 IFNAME=$1
-if [ "$2" == "-i" ]; then
+if [ "$2" = "-i" ]; then
   CONTAINER_IFNAME=$3
   shift 2
 else
@@ -17,6 +17,14 @@ fi
 GUESTNAME=$2
 IPADDR=$3
 MACADDR=$4
+
+if echo $MACADDR | grep -q @
+then
+  VLAN=$(echo $MACADDR | cut -d@ -f2)
+  MACADDR=$(echo $MACADDR | cut -d@ -f1)
+else
+  VLAN=
+fi
 
 [ "$WAIT" ] && {
   while ! grep -q ^1$ /sys/class/net/$CONTAINER_IFNAME/carrier 2>/dev/null
@@ -27,8 +35,8 @@ MACADDR=$4
 
 [ "$IPADDR" ] || {
     echo "Syntax:"
-    echo "pipework <hostinterface> [-i containerinterface] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr]"
-    echo "pipework <hostinterface> [-i containerinterface] <guest> dhcp [macaddr]"
+    echo "pipework <hostinterface> [-i containerinterface] <guest> <ipaddr>/<subnet>[@default_gateway] [macaddr][@vlan]"
+    echo "pipework <hostinterface> [-i containerinterface] <guest> dhcp [macaddr][@vlan]"
     echo "pipework --wait"
     exit 1
 }
@@ -37,11 +45,11 @@ MACADDR=$4
 if [ -d /sys/class/net/$IFNAME ]
 then
     if [ -d /sys/class/net/$IFNAME/bridge ]
-    then 
+    then
         IFTYPE=bridge
         BRTYPE=linux
     elif $(which ovs-vsctl >/dev/null) && $(ovs-vsctl list-br|grep -q ^$IFNAME$)
-    then 
+    then
         IFTYPE=bridge
         BRTYPE=openvswitch
     else IFTYPE=phys
@@ -58,6 +66,11 @@ else
 	    ;;
     esac
 fi
+
+[ $IFTYPE = bridge ] && [ $BRTYPE = linux ] && [ "$VLAN" ] && {
+    echo "VLAN configuration currently unsupported for Linux bridge."
+    exit 1
+}
 
 # Second step: find the guest (for now, we only support LXC containers)
 while read dev mnt fstype options dump fsck
@@ -79,25 +92,23 @@ case "$N" in
 	# If we didn't find anything, try to lookup the container with Docker.
 	if which docker >/dev/null
 	then
-	    DOCKERID=$(docker inspect --format='{{.ID}}' $GUESTNAME)
-	    [ "$DOCKERID" = "<no value>" ] && {
-		echo "Container $GUESTNAME not found, and unknown to Docker."
-		exit 1
-	    }
-	    NN=$(find "$CGROUPMNT" -name "$DOCKERID" | wc -l)
-	    case "$NN" in
-		0)
-		    echo "Container $GUESTNAME doesn't seem to be running."
-		    exit 1
-		    ;;
-		1)
-		    GUESTNAME=$DOCKERID
-		    ;;
-		*)
-		    echo "Multiple cgroup entries for container $GUESTNAME."
-		    exit 1
-		    ;;
-	    esac
+        RETRIES=3
+        while [ $RETRIES -gt 0 ]; do
+      	    DOCKERPID=$(docker inspect --format='{{ .State.Pid }}' $GUESTNAME)
+            [ $DOCKERPID != 0 ] && break
+            sleep 1
+            let RETRIES--
+        done
+
+        [ "$DOCKERPID" = 0 ] && {
+      		echo "Docker inspect returned invalid PID 0"
+    		exit 1
+      	}
+
+        [ "$DOCKERPID" = "<no value>" ] && {
+      		echo "Container $GUESTNAME not found, and unknown to Docker."
+    		exit 1
+      	}
 	else
 	    echo "Container $GUESTNAME not found, and Docker not installed."
 	    exit 1
@@ -114,10 +125,17 @@ esac
 
 if [ "$IPADDR" = "dhcp" ]
 then
-    # We use udhcpc to obtain the DHCP lease, make sure it's installed.
-    which udhcpc >/dev/null || {
-	echo "You asked for DHCP; please install udhcpc first."
-	exit 1
+    # Check for first available dhcp client
+    DHCP_CLIENT_LIST="udhcpc dhcpcd dhclient"
+    for CLIENT in $DHCP_CLIENT_LIST; do
+        which $CLIENT >/dev/null && {
+            DHCP_CLIENT=$CLIENT
+            break
+        }
+    done
+    [ -z $DHCP_CLIENT ] && {
+    	echo "You asked for DHCP; but no DHCP client could be found."
+    	exit 1
     }
 else
     # Check if a subnet mask was provided.
@@ -136,34 +154,47 @@ else
     fi
 fi
 
-NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
-[ "$NSPID" ] || {
-    echo "Could not find a process inside container $GUESTNAME."
-    exit 1
+if [ $DOCKERPID ]; then
+  NSPID=$DOCKERPID
+else
+  NSPID=$(head -n 1 $(find "$CGROUPMNT" -name "$GUESTNAME" | head -n 1)/tasks)
+  [ "$NSPID" ] || {
+      echo "Could not find a process inside container $GUESTNAME."
+      exit 1
+  }
+fi
+
+# Check if an incompatible VLAN device already exists
+[ $IFTYPE = phys ] && [ "$VLAN" ] && [ -d /sys/class/net/$IFNAME.VLAN ] && {
+    [ -z "$(ip -d link show $IFNAME.$VLAN | grep "vlan.*id $VLAN")" ] && {
+        echo "$IFNAME.VLAN already exists but is not a VLAN device for tag $VLAN"
+        exit 1
+    }
 }
 
-mkdir -p /var/run/netns
-rm -f /var/run/netns/$NSPID
+[ ! -d /var/run/netns ] && mkdir -p /var/run/netns
+[ -f /var/run/netns/$NSPID ] && rm -f /var/run/netns/$NSPID
 ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
 
 
 # Check if we need to create a bridge.
 [ $IFTYPE = bridge ] && [ ! -d /sys/class/net/$IFNAME ] && {
-    (ip link set $IFNAME type bridge > /dev/null 2>&1) || (brctl addbr $IFNAME)
+    (ip link add dev $IFNAME type bridge > /dev/null 2>&1) || (brctl addbr $IFNAME)
     ip link set $IFNAME up
 }
 
+MTU=$(ip link show $IFNAME | awk '{print $5}')
 # If it's a bridge, we need to create a veth pair
 [ $IFTYPE = bridge ] && {
-    LOCAL_IFNAME=pl$NSPID$CONTAINER_IFNAME
-    GUEST_IFNAME=pg$NSPID$CONTAINER_IFNAME
-    ip link add name $LOCAL_IFNAME type veth peer name $GUEST_IFNAME
+    LOCAL_IFNAME="v${CONTAINER_IFNAME}pl${NSPID}"
+    GUEST_IFNAME="v${CONTAINER_IFNAME}pg${NSPID}"
+    ip link add name $LOCAL_IFNAME mtu $MTU type veth peer name $GUEST_IFNAME mtu $MTU
     case "$BRTYPE" in
         linux)
             (ip link set $LOCAL_IFNAME master $IFNAME > /dev/null 2>&1) || (brctl addif $IFNAME $LOCAL_IFNAME)
             ;;
         openvswitch)
-            ovs-vsctl add-port $IFNAME $LOCAL_IFNAME
+            ovs-vsctl add-port $IFNAME $LOCAL_IFNAME ${VLAN:+"tag=$VLAN"}
             ;;
     esac
     ip link set $LOCAL_IFNAME up
@@ -171,17 +202,27 @@ ln -s /proc/$NSPID/ns/net /var/run/netns/$NSPID
 
 # If it's a physical interface, create a macvlan subinterface
 [ $IFTYPE = phys ] && {
+    [ "$VLAN" ] && {
+        [ ! -d /sys/class/net/$IFNAME.$VLAN ] && {
+            ip link add link $IFNAME name $IFNAME.$VLAN mtu $MTU type vlan id $VLAN
+        }
+
+        ip link set $IFNAME up
+        IFNAME=$IFNAME.$VLAN
+    }
     GUEST_IFNAME=ph$NSPID$CONTAINER_IFNAME
-    ip link add link $IFNAME dev $GUEST_IFNAME type macvlan mode bridge
+    ip link add link $IFNAME dev $GUEST_IFNAME mtu $MTU type macvlan mode bridge
     ip link set $IFNAME up
 }
 
 ip link set $GUEST_IFNAME netns $NSPID
 ip netns exec $NSPID ip link set $GUEST_IFNAME name $CONTAINER_IFNAME
-[ "$MACADDR" ] && ip netns exec $NSPID ip link set $CONTAINER_IFNAME address $MACADDR
+[ "$MACADDR" ] && ip netns exec $NSPID ip link set dev $CONTAINER_IFNAME address $MACADDR
 if [ "$IPADDR" = "dhcp" ]
 then
-    ip netns exec $NSPID udhcpc -qi $CONTAINER_IFNAME
+    [ $DHCP_CLIENT = "udhcpc"  ] && ip netns exec $NSPID $DHCP_CLIENT -qi $CONTAINER_IFNAME -x hostname:$GUESTNAME
+    [ $DHCP_CLIENT = "dhclient"  ] && ip netns exec $NSPID $DHCP_CLIENT $CONTAINER_IFNAME -H $GUESTNAME
+    [ $DHCP_CLIENT = "dhcpcd"  ] && ip netns exec $NSPID $DHCP_CLIENT -q $CONTAINER_IFNAME -h $GUESTNAME
 else
     ip netns exec $NSPID ip addr add $IPADDR dev $CONTAINER_IFNAME
     [ "$GATEWAY" ] && {
@@ -196,9 +237,35 @@ fi
 # Give our ARP neighbors a nudge about the new interface
 if which arping > /dev/null 2>&1
 then
-    IPADDR=$(echo $IPADDR | cut -d/ -f1) 
-    ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $IPADDR > /dev/null 2>&1
+    # Wait until the interface is up
+    while ! ip netns exec $NSPID ethtool $CONTAINER_IFNAME | grep Link | grep -q 'Link detected: yes$' 2>/dev/null; do
+        sleep 1
+    done
+    IPADDR=$(echo $IPADDR | cut -d/ -f1)
+    ip netns exec $NSPID arping -c 1 -A -I $CONTAINER_IFNAME $IPADDR > /dev/null 2>&1 || true
 else
     echo "Warning: arping not found; interface may not be immediately reachable"
 fi
+
+[ "$GATEWAY" ] && {
+    if which arp > /dev/null 2>&1
+    then
+        ping -c 1 $GATEWAY > /dev/null 2>&1 # To make sure gateway ARP entry on host is populated
+        GATEWAY_MAC=`arp -an $GATEWAY | cut -d' ' -f4`
+        # Wait until gateway entry appears in the container's ARP table
+        while : ; do
+            ip netns exec $NSPID arp -s $GATEWAY $GATEWAY_MAC
+            if ip netns exec $NSPID arp -n $GATEWAY | awk '{print $3}' | grep -q $GATEWAY_MAC
+            then
+							break
+						fi
+            sleep 1
+        done
+    else
+        echo "Warning: arp not found; interface may not be immediately reachable"
+    fi
+}
+
+# Remove NSPID to avoid `ip netns` catch it.
+[ -f /var/run/netns/$NSPID ] && rm -f /var/run/netns/$NSPID
 exit 0
